### ISSUE TITLE
Highlight specific fields in Product Import that haven't been entered

### ISSUE THREAD

**Issue by cbusillo** [Shiny-Computers/odoo_addons_shiny#34]

**Comment by cbusillo** [comment]
Price, weight, name

**Comment by cbusillo** [comment]
Please test.  Make suggestions or close.  Thanks

**Comment by Mbanks89** [comment]
Highlight you’re asking me to test I do not believe is working.  I could be wrong.  I might need a screenshot or to see that one in person

**Comment by Mbanks89** [comment]
Tested

**Comment by Mbanks89** [comment]
Tested
