### ISSUE TITLE
The Shopify Sync is no longer Checking Sales Channels 

### ISSUE THREAD

**Issue by Mbanks89** [Shiny-Computers/odoo_addons_shiny#69]
It looks like on August 2nd, the Shopify Sync from odoo stopped adding the sales channels on shopify.  Please see attached 
![Screenshot 2023-08-14 at 7 22 53 PM](https://github.com/Shiny-Computers/odoo_addons_shiny/assets/138520454/4f2ac30d-2230-4faa-9fac-19a352af79e1)
![Screenshot 2023-08-14 at 7 22 45 PM](https://github.com/Shiny-Computers/odoo_addons_shiny/assets/138520454/21fd7fe7-d2e0-47d5-9b0b-7007fc90ebed)

**Comment by Mbanks89** [comment]
I already edited all of the Skus in shopify and fixed them.   So the screen shots show them as checked, but prior to that they were not.

**Comment by Mbanks89** [comment]
Will have to test later today.   Not sure if that would fix any listing that did not have the sales channels added.   But if it was supposed to, it has not.  If its only supposed to do that on the first sync / push.  Then I will confirm today

**Comment by Mbanks89** [comment]
Does not appear to be working 


![Screen Shot 2023-08-22 at 10 0
![Screen Shot 2023-08-22 at 10 06 56 AM](https://github.com/Shiny-Computers/odoo_addons_shiny/assets/138520454/ca9e1a90-545d-445f-a01d-e21755333ad9)
6 44 AM](https://github.com/Shiny-Computers/odoo_addons_shiny/assets/138520454/b574f03e-1cae-458e-a456-ba317df71f83)

**Comment by cbusillo** [comment]
Nice.
